import random

nature, animals, fruits, food = (
    ["moonlight", "sunlight", "forest", "mountain", "desert", "cave", "beach"],
    ["columbidae", "elephant", "hippopotamus", "rabbit", "dodo", "zebra", "tiger", "chicken"],
    ["avocado", "watermelon", "apricot", "pineapple", "blackberry", "raspberry", "blueberry"],
    ["sausages", "popcorn", "icecream", "pizza", "hamburger", "cheese"])
themeoverview = ["nature", "animals", "fruits", "food"]
randomtheme = [nature, animals, fruits, food]

def chose_theme():
    while True:
        print("Choose your theme...")
        for x in range(0, len(themeoverview)):
            print(str(x + 1) + "." + themeoverview[x])
        print(str(len(themeoverview) + 1) + ".random")
        try:
            theme = int(input())
            if theme > (len(themeoverview) + 1) or theme < 0:
                print("\nPlease enter a valid option :)\n")
            else:
                break
        except:
            print("\nPlease enter a valid option :)\n")
    return theme

def theme_setup():
    themenum = chose_theme()
    match themenum:
        case 1:
            theme = nature
        case 2:
            theme = animals
        case 3:
            theme = fruits
        case 4:
            theme = food
        case 5:
            theme = randomtheme[random.randint(0, len(randomtheme) - 1)]
    word = theme[random.randint(0, len(theme) - 1)].upper()
    return word

def play(word):
    letter_line = "_" * len(word)
    guessed = False
    guessed_letters = []
    guessed_words = []
    fail = 10
    print("Hangman")
    print(man(fail))
    print(letter_line)
    print(word)
    print('\n')
    while not guessed and fail > 0:
        guess = input("\nWhat letter?\n").upper()
        if len(guess) == 1 and guess.isalpha():
            if guess in guessed_letters:
                print("Already Used Letter", guess)
            elif guess not in word:
                print(guess, "Incorrect")
                fail -= 1
                guessed_letters.append(guess)
            else:
                print("Correct", guess, "is in the word!")
                guessed_letters.append(guess)
                complete_letter_line = list(letter_line)
                letter_position = [i for i, letter in enumerate(word) if letter == guess]
                for index in letter_position:
                    complete_letter_line[index] = guess
                letter_line = "".join(complete_letter_line)
                if "_" not in letter_line:
                    guessed = True
        elif len(guess) == len(word) and guess.isalpha():
            if guess in guessed_words:
                print("Already used word", guess)
            elif guess != word:
                print(guess, "is not the word")
                fail -= 1
                guessed_words.append(guess)
            else:
                guessed = True
                letter_line = word
        else:
            print("Can't Be Read")
        print(man(fail))
        print(letter_line)
        print('\n')
    if guessed:
        print("you won!")
        print(letter_line)
    else:
        print("bleh x_x\nyou lost...")

def man(fail):
    stage = [
                """
                ....................
                ..._______________..
                ........|......|....
                ........|......|....
                ........O......|....
                ....../.|.\....|....
                ......./.\.....|....
                ...............|....
                .............-----..
                """,
                """
                ....................
                ..._______________..
                ........|......|....
                ........|......|....
                ........O......|....
                ....../.|.\....|....
                ......./.......|....
                ...............|....
                .............-----..
                """,
                """
                ....................
                ..._______________..
                ........|......|....
                ........|......|....
                ........O......|....
                ....../.|.\....|....
                ...............|....
                ...............|....
                .............-----..
                """,
                """            
                ....................
                ..._______________..
                ........|......|....
                ........|......|....
                ........O......|....
                ....../.|......|....
                ...............|....
                ...............|....
                .............-----..
                """,
                """
                ....................
                ..._______________..
                ........|......|....
                ........|......|....
                ........O......|....
                ........|......|....
                ...............|....
                ...............|....
                .............-----..
                """,
                """
                ....................
                ..._______________..
                ........|......|....
                ........|......|....
                ........O......|....
                ...............|....
                ...............|....
                ...............|....
                .............-----..
                """,
                """
                ....................
                ..._______________..
                ........|......|....
                ........|......|....
                ...............|....
                ...............|....
                ...............|....
                ...............|....
                .............-----..
                """,
                """
                ....................
                ..._______________..
                ...............|....
                ...............|....
                ...............|....
                ...............|....
                ...............|....
                ...............|....
                .............-----..
                """,
                """
                ....................
                ....................
                ...............|....
                ...............|....
                ...............|....
                ...............|....
                ...............|....
                ...............|....
                .............-----..
                """,
                """
                ....................
                ....................
                ....................
                ....................
                ....................
                ....................
                ....................
                ....................
                .............-----..
                """,
                """
                     ....................
                     ....................
                     ....................
                     ....................
                     ....................
                     ....................
                     ....................
                     ....................
                     ....................
                """
                ]
    return stage[fail]

def main():
    word = theme_setup()
    play(word)
    while input("PLAY AGAIN Y/N").upper() == "Y":
        word = theme_setup()
        play(word)

if __name__ == "__main__":
    main()